<?php
// $Id$

/**
 * @file
 * Holds data for bookmarklets.
 */
$columns = array(
  // column 1
  array(
    // IMDb External Reviews
    array(
      'title' => 'IMDb',
      'subtitle' => 'External Reviews',
      'body' => 'When in a IMDb title page, jump to External Reviews.',
      'script' => "d=document.location.href;
        if (d.indexOf('imdb.com/title') != -1) {
          pos = d.indexOf('?');
          if (pos != -1) {
            d = d.substr(0, pos);
          }
          document.location.href = d + 'externalreviews';
        }",

      'link' => 'xr',
      'icon' => 'imdb',
    ),
    // IMDb store new film
    array(
      'title' => 'IMDb',
      'subtitle' => 'Add title to NMovies',
      'body' => "When in a IMDb title page, open NMovies in another tab, while adding the movie to my catalogue.",
      'script' => "
        url = 'http://nmovies:8080?newfilm=';
        if (document.location.href.indexOf('imdb.com/title') != -1)
          window.open(url + document.location.href);",
      'link' => 'title',
      'icon' => 'nmovies',
    ),
    // Google Bookmarks popup
    array(
      'title' => 'Google',
      'subtitle' => 'Bookmark',
      'body' => 'Open a dialog to save the current webpage as your Google bookmark. Choose your tags',
      'file' => 'google_bm.js',
      'link' => 'bm',
      'icon' => 'google',
    ),
    // Flickr Hack
    array(
      'title' => 'Flickr',
      'subtitle' => 'Download photo',
      'body' => "When in the 'view all sizes' page, save (protected) photo.",
      'script' => "
        p = document.getElementById('allsizes-photo'),
        img = p.getElementsByTagName('img')[0],
        src = img.getAttribute('src');
        src = src.substr(0, src.lastIndexOf('.'((;
        document.location.href = src + '_d.jpg';
      ",
      'link' => 'Get flickr',
      'icon' => 'flickr',
    ),
  // column 3
  array(
    // NOS Teletekst in a popup
    array(
      'title' => 'Teletekst',
      'subtitle' => 'NOS Teletekst in popup',
      'body' => '',
      'script' => "
        specs = 'width=740,height=540,resizable=0';
        url = 'http://nos.nl/teletekst/#101_01';
        window.open(url, 'w', specs);",
      'link' => 'tt',
      'icon' => 'nos'
    ),
    // NOS Journaal24 in a popup
    array(
      'title' => 'Journaal',
      'subtitle' => 'NOS Journaal in popup',
      'body' => '',
      'script' => "
        url = 'http://nos.nl/nieuws/live/journaal24';
        specs = 'width=700,height=510,resizable=0';
        window.open(url, 'w', specs);",
      'link' => 'nj',
      'icon' => 'journaal24'
    ),
    // Open images on an index page
    array(
      'title' => 'Image Opener',
      'subtitle' => 'Load images on index page',
      'body' => "",
      'file' => 'opener.js',
      'link' => 'open',
      'icon' => 'image'
    ),
  )
)
);